undpaul\MarioKartBundle\Entity\Game:
    type: entity
    table: mariokart_game
    repositoryClass: undpaul\MarioKartBundle\Entity\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        delta:
            type: integer
    manyToOne:
        round:
          targetEntity: undpaul\MarioKartBundle\Entity\Round
          inversedBy: games
    oneToMany:
        races:
            targetEntity: undpaul\MarioKartBundle\Entity\Race
            mappedBy: game
    lifecycleCallbacks: {  }
