undpaul\MarioKartBundle\Entity\RaceResultItem:
    type: entity
    table: null
    repositoryClass: undpaul\MarioKartBundle\Entity\RaceResultItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pos_rel:
            type: integer
        pos_abs:
            type: integer
        pts_rel:
            type: integer
        pts_abs:
            type: integer
    manyToOne:
        race:
          targetEntity: undpaul\MarioKartBundle\Entity\Race
          inversedBy: results
        participation:
          targetEntity: undpaul\MarioKartBundle\Entity\Participation
          inversedBy: results
    lifecycleCallbacks: {}

