undpaul\MarioKartBundle\Entity\Race:
    type: entity
    table: null
    repositoryClass: undpaul\MarioKartBundle\Entity\RaceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        delta:
            type: integer
    manyToOne:
        game:
          targetEntity: undpaul\MarioKartBundle\Entity\Game
          inversedBy: races
    oneToMany:
        results:
            targetEntity: undpaul\MarioKartBundle\Entity\RaceResultItem
            mappedBy: race
            cascade: ['all']
    lifecycleCallbacks: {  }
