undpaul\MarioKartBundle\Entity\RaceResultItem:
    type: entity
    table: mariokart_race_result_item
    repositoryClass: undpaul\MarioKartBundle\Entity\RaceResultItemRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        pos_rel:
            type: integer
        pos_abs:
            type: integer
        pts_rel:
            type: integer
        pts_abs:
            type: integer
    manyToOne:
        race:
          targetEntity: undpaul\MarioKartBundle\Entity\Race
          inversedBy: results
        player:
          targetEntity: undpaul\MarioKartBundle\Entity\Player
    lifecycleCallbacks: {  }
