undpaul\MarioKartBundle\Entity\Round:
    type: entity
    table: null
    repositoryClass: undpaul\MarioKartBundle\Entity\RoundRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        delta:
            type: integer
    manyToOne:
        tournament:
          targetEntity: undpaul\MarioKartBundle\Entity\Tournament
          inversedBy: rounds
    oneToMany:
        games:
            targetEntity: undpaul\MarioKartBundle\Entity\Game
            mappedBy: round
            cascade: ['all']
    lifecycleCallbacks: {  }
