undpaul\MarioKartBundle\Entity\Tournament:
    type: entity
    table: null
    repositoryClass: undpaul\MarioKartBundle\Entity\TournamentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
            column: Name
    oneToMany:
        rounds:
          targetEntity: undpaul\MarioKartBundle\Entity\Round
          mappedBy: tournament
          cascade: [all]
        participations:
          targetEntity: undpaul\MarioKartBundle\Entity\Participation
          mappedBy: tournament
          cascade: [all]
    lifecycleCallbacks: {  }
