<?php

namespace undpaul\MarioKartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaceResultItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceResultItemRepository extends EntityRepository
{
}
