upmk_homepage:
    path:     /
    defaults: { _controller: undpaulMarioKartBundle:Default:index }

upmk_legacy:
    path:     /legacy
    defaults: { _controller: undpaulMarioKartBundle:Legacy:index }

upmk_tournament_index:
    path:     /tournament
    defaults: { _controller: undpaulMarioKartBundle:Tournament:index }

upmk_tournament_new:
    path:     /tournament/new
    defaults: { _controller: undpaulMarioKartBundle:Tournament:new }

upmk_tournament_view:
    path:     /tournament/{tournament_id}
    defaults: { _controller: undpaulMarioKartBundle:Tournament:view }
    requirements: { tournament_id:  \d+ }

upmk_tournament_remove:
    path:     /tournament/{tid}/remove
    defaults: { _controller: undpaulMarioKartBundle:Tournament:remove }
    requirements: { tid:  \d+ }

upmk_tournament_add_player:
    path:     /tournament/{tournament_id}/player/add
    defaults: { _controller: undpaulMarioKartBundle:Tournament:addPlayer }
    requirements: { tournament_id:  \d+ }

upmk_player_index:
    path:     /player
    defaults: { _controller: undpaulMarioKartBundle:Player:index }

upmk_player_new:
    path:     /player/new
    defaults: { _controller: undpaulMarioKartBundle:Player:new }

upmk_round_view:
    path:     /round/{round_id}
    defaults: { _controller: undpaulMarioKartBundle:Round:view }

upmk_round_generate:
    path:     /tournament/{tournament_id}/round/generate
    defaults: { _controller: undpaulMarioKartBundle:Round:generate }

upmk_round_remove:
    path:     /round/{round_id}/remove
    defaults: { _controller: undpaulMarioKartBundle:Round:remove }

upmk_game_view:
    path:     /game/{game_id}
    defaults: { _controller: undpaulMarioKartBundle:Game:view }

upmk_game_edit:
    path:     /game/{game_id}/edit
    defaults: { _controller: undpaulMarioKartBundle:Game:edit }

upmk_participation_view:
    path:     /participation/{pid}
    defaults: { _controller: undpaulMarioKartBundle:Participation:view }

upmk_participation_remove:
    path:     /participation/{pid}/remove
    defaults: { _controller: undpaulMarioKartBundle:Participation:remove }
