services:
    upmk.pointrules:
        class: undpaul\MarioKartBundle\Service\PointRules
        arguments: []

    upmk.resultitem:
        class: undpaul\MarioKartBundle\Listener\ResultItemListener
        arguments: [@upmk.pointrules]
        tags:
            - { name: doctrine.event_listener, event: preFlush }

    upmk.roundgenerator:
        class: undpaul\MarioKartBundle\Service\RoundGenerator
        arguments: [@doctrine]
